version: "3.0"

networks:
  twentytwobot-network:
    driver: bridge

services:
  app:
    build: "./"
    command: ["npm", "start"]
    environment:
      - TWITCHTV_AUTHENTICATION_TOKEN=${TWITCHTV_AUTHENTICATION_TOKEN}
      - TWITCHTV_CHANNELS=${TWITCHTV_CHANNELS:-22atreyu22}
      - TWITCHTV_USERNAME=${TWITCHTV_USERNAME:-twentytwobot}
    networks:
      - twentytwobot-network
    volumes:
      - ./:/home/node/application/app:delegated
      - /home/node/application/app/node_modules/
