CREATE TABLE `timer`(
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `intervalSeconds` SMALLINT UNSIGNED NOT NULL DEFAULT 1800
) ENGINE=InnoDB;

CREATE TABLE `timer_message`(
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `timerID` INT UNSIGNED,
  `message` VARCHAR(500) NOT NULL,
  FOREIGN KEY(`timerID`) REFERENCES `timer`(`id`)
) ENGINE=InnoDB;
