CREATE TABLE `user`(
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `dateCreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateUpdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `username` VARCHAR(25) NOT NULL,
  `displayName` VARCHAR(25) NOT NULL,
  `twitchID` VARCHAR(32) NOT NULL,
  `lastGamePlayed` VARCHAR(255) NOT NULL,
  `isBot` TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE INDEX(`username`)
) ENGINE = InnoDB;
