CREATE TABLE `user_log`(
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `userID` INT UNSIGNED NOT NULL,
  `dateJoined` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dateParted` TIMESTAMP NULL,
  FOREIGN KEY (`userID`) REFERENCES `user`(`id`)
) ENGINE=InnoDB;
