CREATE TABLE `points`(
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `dateUpdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `userID` INT UNSIGNED NOT NULL UNIQUE,
  `points` BIGINT UNSIGNED NOT NULL DEFAULT 22,
  FOREIGN KEY(`userID`) REFERENCES `user`(`id`)
) ENGINE=InnoDB;
