const botUsers = [
  'alienconglomeration',
  'commanderroot',
  'rogueg1rl',
  'streamelements',
  '0ax2',
  'aservicestop',
  'iizzybeth',
  'lurxx',
];

const knownStreamers = [
  '22atreyu22',
  'jamesgeheimergeheimagent',
  'acidic_virus_',
  'tomasina',
  'tinabug02',
  'deadbug_uk',
  'mosterdpottv',
  'skobbejakkals',
  'ruakgorth',
  'scruffyriles',
  'atheenon',
  'rand_althor1966',
  'chefmaria',
  'ladyqxx',
  'miamatsumo',
  'cconkyy',
  'bladescj',
  'wafflemaus',
  'sqrlyfrost',
  'perfecttrip',
  'tslpolt',
  'street_og',
  'almakay98',
  'c0olk',
  'theoriginalmrboring',
  'grimfirexd',
  'ryfyguy',
  'packerbacker523',
  'stylezaknafein',
  'esherya',
  'ishhhhxo',
  'meispamlange',
  'when_dyy',
  'someoldfart',
  'x3catsincoat',
  'guntech1',
];

module.exports = {
  botUsers,
  knownStreamers,
};
