name: Static tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Test formatting
        run: npm run test:format
        working-directory: ./server
      
      - name: Test linting
        run: npm run test:lint
        working-directory: ./server
      
      - name: Test types
        run: npm run test:types
        working-directory: ./server
